# Generated by Django 3.0.5 on 2020-04-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='content',
            field=models.CharField(default='SOME STRING', max_length=1000),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='subject',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
    ]
