# Generated by Django 3.0.5 on 2020-05-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200430_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='user',
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='file_manegement/file'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
